### PR TITLE
Update Login, Authenticate, and GetValue methods with new REST endpoints

### PR DESCRIPTION
**Pull request by treyyoder**
**What does this pull request do?**
Fixes a few REST API calls: (login, auth, fetching secrets)

**What background context can you provide?**
A client requested a demonstration of this API, however it does not work as-is.  I updated a few methods to fix login, auth, and to be able to demonstrate fetching secrets.

**Where should the reviewer start?**
Manual testing.

**How should this be manually tested?**
You can run this solution in Visual Studio:

1. _example.csproj_
Usage: 
`<applianceHostName> <applianceCertificatePath> <username> <password> <variableId> <hostFactoryToken> <account> <useSSL>` 
ex. test args:
`conjur.acme.com conjur.crt admin P@!!w0rD1234 app1/db_password hostfactorytoken acme false`

1. _demo.csproj_
Usage: 
`<applianceHostName> <applianceCertificatePath> <username> <password> <variableId> <account> <useSSL>`
ex. test args:
`conjur.acme.com conjur.crt host/apps/app1 1cs5y9w3ea9ywq3670fwc1dwv0rj2t244v12zxwm9z1gnfk111qccryj apps/app1/db_password acme false`

**Additional Comments:**
1. Created a demo project for client demonstration. (This could be done with, but I wanted a place I could initally template fixes and wasn't sure if example was part of some other process or usage)

1. Added a parameter to disable SSL.

### CODE REVIEW

**Comment by izgeri** [comment]
Hey @treyyoder! Thanks so much for submitting this - we'll be taking a look through it today, and we'll try to leave a batch of feedback so that if we have any requested changes, we can hopefully resolve them with as few back-and-forths as possible. I really appreciate your help in making this project better!!

**Comment by JakeQuilty** [comment]
Hey @treyyoder have you checked out the [ca-conjur-api-dotnet-v5-master](https://github.com/cyberark/conjur-api-dotnet/tree/ca-conjur-api-dotnet-v5-master) branch?

**Comment by izgeri** [comment]
To give a little more context @treyyoder - since you submitted your contribution I learned about some other work that had been done on this project but not yet merged into master yet. It includes **a lot** of functionality - we documented it in [this issue](https://github.com/cyberark/conjur-api-dotnet/issues/41#issue-609129921) the methods that are available. Can you take a look? I think you will like the changes there, and we're looking to merge that branch into master. If you have any feedback about the branch and/or how to integrate your changes into it, we'd be happy to work with you on it. Can you please take a look and let us know what you think?

**Comment by treyyoder** [comment]
@izgeri I tested the [ca-conjur-api-dotnet-v5-master](https://github.com/cyberark/conjur-api-dotnet/tree/ca-conjur-api-dotnet-v5-master) branch and it address the initial issues that I had.  I still want to test the host factory functionality.  In interim, the only suggestions I have are with the example application:

1. Do not update the secret [here](https://github.com/cyberark/conjur-api-dotnet/blob/ca-conjur-api-dotnet-v5-master/example/Program.cs#L99).  This overwrites the existing secret abrubtly.  I'd prefer to see this in a documented subsequent step later in the example program.

2. As shown in my PR, disabling SSL is useful when working in a demo environment.

I can submit a PR against that branch if you agree.

**Comment by izgeri** [comment]
@treyyoder we're working to get the `ca-conjur-api-dotnet-v5-master` branch merged into master this week - I think once that's done, having you revise this PR so that it works with the current functionality on master but updates the example / demo flows as you're recommending would be great!

One thing I noticed in your PR as I'm looking right now - what do you think about just adding subfolders in the `example` dir, putting the current example in a folder there, and adding your demo flow to its own folder in `example/demo` (or similar) too? The benefit would be one place where people could look for a couple of different ways to explore the project. We could even add a light README to the `example` folder to describe what's in the different sub-folders.

Let me know what you think. Thanks!

**Comment by izgeri** [comment]
@treyyoder it took us some time to get it done, but the master branch now holds the content with support for Conjur OSS and DAP!

are you interested in updating this PR to work with the updated client? in particular, I'm wondering if you would like to update the current example to work the way you propose above:
> Do not update the secret here. This overwrites the existing secret abrubtly. I'd prefer to see this in a documented subsequent step later in the example program.

in addition, what do you think about my suggestion?
> what do you think about just adding subfolders in the example dir, putting the current example in a folder there, and adding your demo flow to its own folder in example/demo (or similar) too? The benefit would be one place where people could look for a couple of different ways to explore the project. We could even add a light README to the example folder to describe what's in the different sub-folders

**Comment by treyyoder** [comment]
@izgeri Yes, I think adding subfolders with different examples would be beneficial.  Ill pull the latest master and refactor my branch to work with it.  I'll try to have you a PR by the end of the week.

**Comment by izgeri** [comment]
@treyyoder just checking in to see if you're still planning to rework this PR to work with the updated client. Please let me know if not so that we can close this PR. Thanks!

**Comment by treyyoder** [comment]
@izgeri I do plan to work on this, but haven't had time recently.  If you want to close this PR, I can open a new one when I get back to this.

**Comment by izgeri** [comment]
thanks @treyyoder. I'll close this one for now - I look forward to seeing your new PR once you're ready to submit it :)

**Pull request closed without merging**
