### PR TITLE
Thread safe api key authenticator

### PR DESCRIPTION
**Pull request by acher82**
For VaultConjurSychronizer we need that Variable.AddValue action will be a thread safe.
In general an AddValue flow looks thread safe except the part of token refresh.
I simplified token expiration mechanism and add to thread safety.

### CODE REVIEW

**Comment by dividedmind** [comment]
Now that I think about it some more, the lock is overkill as well. The race can be removed simply by using `Interlocked.CompareExchange` when accessing `tokenExpired` boolean. Let me know if you need any guidance on how to do that (or if you'd rather I did it :) ).

BTW, thanks for noticing the problem!

**Comment by acher82** [comment]
Suppose we have two threads.
What will happened when the first thread gets a token and then the second replaces a token before the first one uses it.
Does the "old" token is still valid?

**Comment by dividedmind** [comment]
Yes, perfectly valid.

**Comment by acher82** [comment]
How long token actually is valid from Conjur point of view after "expiration" (7 minutes 30 seconds)

**Comment by dividedmind** [comment]
Tokens are valid for eight minutes; dotnet API refreshes after 7'30", some other libraries (notably Ruby API) refreshes after 4'. Either way there's no risk that a thread will end up with an invalid token due to this race (unless it can connect for 30 seconds, at which point it probably has bigger problems). The only (relatively harmless) issue might be unnecessarily refreshing the token twice on 7'30" point (by two separate threads); using atomic exchange for the boolean will ensure that can't happen.

**Comment by acher82** [comment]
Interlocked.CompareExchange has no bool version.
I will need to change tokenExpired to int.
Am I right?

**Pull request closed without merging**
